### PR TITLE
Bump Lumos for improved M1 Macs support.

### PR DESCRIPTION
**Pull request by Kuzirashi**
This PR is required so godwoken-examples or any repository using polyjuice-provider as dependency can run on Mac M1.

cc @RetricSu

### CODE REVIEW

**Comment by RetricSu** [comment]
just curious, I am using M1 to develop this repo, and [this example](https://github.com/nervosnetwork/polyjuice-provider). I did not realized the lumos unsupported issue. what's the expected result for this? Maybe I have different setup on my machine?

**Comment by Kuzirashi** [comment]
@RetricSu 

I'm not sure, but on Mac M1 Mini you can't install polyjuice-provider as dependency, because it depends on old lumos with cpu restriction.

image

You can see it is true by looking at polyjuice-provider yarn.lock file: https://github.com/nervosnetwork/polyjuice-provider/blob/main/yarn.lock#L174

---

Maybe it works for you because you have a workaround on your system (Example workaround: https://www.jurnalanas.com/node-js-mac-m1/)

**Comment by RetricSu** [comment]
yeap, indeed it is that arch workaround. will release a new version after this pr merged.

**Comment by Kuzirashi** [comment]
@RetricSu

Okay, leaving review and merging to you.

**Pull request merged**
